# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20160916_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_img',
        ),
        migrations.AlterField(
            model_name='postfile',
            name='permissions',
            field=models.CharField(choices=[('1', '公开'), ('2', '登陆可见')], max_length=1),
        ),
    ]
