# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20160916_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, '赛事公告'), (2, '技术讨论'), (3, '各路水贴')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='permissions',
            field=models.CharField(choices=[('1', '公开'), ('2', '登陆可见')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
