# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20160916_2307'),
        ('community', '0008_auto_20160917_1357'),
    ]

    operations = [
    ]
