# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_merge_20160918_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', '赛事公告'), ('2', '技术讨论'), ('3', '各路水贴')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='permissions',
            field=models.CharField(choices=[('2', '登陆可见'), ('1', '公开')], max_length=1),
        ),
    ]
