# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20160920_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replycount',
        ),
    ]
