# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_auto_20160930_1919'),
        ('community', '0018_auto_20160930_1632'),
    ]

    operations = [
    ]
