# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20160925_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(choices=[('D', 'DSP'), ('M', 'MCU'), ('F', 'FPGA'), ('', 'Unknown')], default='', max_length=1),
        ),
    ]
