# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20160925_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(choices=[('D', 'DSP'), ('M', '单片机'), ('F', 'FPGA')], default='M', max_length=1),
        ),
    ]
