# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_pre_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='first_time',
            field=models.IntegerField(choices=[(-1, 'None')], default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='pre_time',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'Nov Sat Nov 12 09:30:00 2016---09:36'), (1, 'Nov Sat Nov 12 09:36:00 2016---09:42'), (2, 'Nov Sat Nov 12 09:42:00 2016---09:48'), (3, 'Nov Sat Nov 12 09:48:00 2016---09:54'), (4, 'Nov Sat Nov 12 09:54:00 2016---10:00'), (5, 'Nov Sat Nov 12 10:00:00 2016---10:06'), (6, 'Nov Sat Nov 12 10:06:00 2016---10:12'), (7, 'Nov Sat Nov 12 10:12:00 2016---10:18'), (8, 'Nov Sat Nov 12 10:18:00 2016---10:24'), (9, 'Nov Sat Nov 12 10:24:00 2016---10:30'), (10, 'Nov Sat Nov 12 10:30:00 2016---10:36'), (11, 'Nov Sat Nov 12 10:36:00 2016---10:42'), (12, 'Nov Sat Nov 12 10:42:00 2016---10:48'), (13, 'Nov Sat Nov 12 10:48:00 2016---10:54'), (14, 'Nov Sat Nov 12 10:54:00 2016---11:00'), (15, 'Nov Sat Nov 12 11:00:00 2016---11:06'), (16, 'Nov Sat Nov 12 11:06:00 2016---11:12'), (17, 'Nov Sat Nov 12 11:12:00 2016---11:18'), (18, 'Nov Sat Nov 12 11:18:00 2016---11:24'), (19, 'Nov Sat Nov 12 11:24:00 2016---11:30'), (20, 'Nov Sat Nov 12 13:30:00 2016---13:36'), (21, 'Nov Sat Nov 12 13:36:00 2016---13:42'), (22, 'Nov Sat Nov 12 13:42:00 2016---13:48'), (23, 'Nov Sat Nov 12 13:48:00 2016---13:54'), (24, 'Nov Sat Nov 12 13:54:00 2016---14:00'), (25, 'Nov Sat Nov 12 14:00:00 2016---14:06'), (26, 'Nov Sat Nov 12 14:06:00 2016---14:12'), (27, 'Nov Sat Nov 12 14:12:00 2016---14:18'), (28, 'Nov Sat Nov 12 14:18:00 2016---14:24'), (29, 'Nov Sat Nov 12 14:24:00 2016---14:30'), (30, 'Nov Sat Nov 12 14:30:00 2016---14:36'), (31, 'Nov Sat Nov 12 14:36:00 2016---14:42'), (32, 'Nov Sat Nov 12 14:42:00 2016---14:48'), (33, 'Nov Sat Nov 12 14:48:00 2016---14:54'), (34, 'Nov Sat Nov 12 14:54:00 2016---15:00'), (35, 'Nov Sat Nov 12 15:00:00 2016---15:06'), (36, 'Nov Sat Nov 12 15:06:00 2016---15:12'), (37, 'Nov Sat Nov 12 15:12:00 2016---15:18'), (38, 'Nov Sat Nov 12 15:18:00 2016---15:24'), (39, 'Nov Sat Nov 12 15:24:00 2016---15:30'), (40, 'Nov Sat Nov 12 15:30:00 2016---15:36'), (41, 'Nov Sat Nov 12 15:36:00 2016---15:42'), (42, 'Nov Sat Nov 12 15:42:00 2016---15:48'), (43, 'Nov Sat Nov 12 15:48:00 2016---15:54'), (44, 'Nov Sat Nov 12 15:54:00 2016---16:00'), (45, 'Nov Sat Nov 12 16:00:00 2016---16:06'), (46, 'Nov Sat Nov 12 16:06:00 2016---16:12'), (47, 'Nov Sat Nov 12 16:12:00 2016---16:18'), (48, 'Nov Sat Nov 12 16:18:00 2016---16:24'), (49, 'Nov Sat Nov 12 16:24:00 2016---16:30'), (50, 'Nov Sat Nov 12 16:30:00 2016---16:36'), (51, 'Nov Sat Nov 12 16:36:00 2016---16:42'), (52, 'Nov Sat Nov 12 16:42:00 2016---16:48'), (53, 'Nov Sat Nov 12 16:48:00 2016---16:54'), (54, 'Nov Sat Nov 12 16:54:00 2016---17:00')], default=-1),
        ),
    ]
