# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20161117_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='other_fuhuo_time',
        ),
        migrations.AlterField(
            model_name='team',
            name='fuhuo_time',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (1, '周六'), (2, '周日'), (3, '服从调剂')], default=-1, null=True),
        ),
    ]
