# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20160820_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='filename',
            field=models.CharField(default='File', max_length=40),
        ),
    ]
