# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_notification_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='filename',
        ),
    ]
