# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
