# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160918_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='head_images/default.png', upload_to='head_images'),
        ),
    ]
