# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='/home/alxl/workspace/EE/Electronic-Design-Competition-Web/EDCW/media/head_images/custom.png', upload_to='head_images'),
        ),
    ]
