# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160925_1405'),
        ('login', '0005_auto_20160926_1838'),
    ]

    operations = [
    ]
